version: 2.1

# Define the jobs we want to run for this project
jobs:
  test-variable:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo $PRACTICE_VARIABLE
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Hello"
  say-hi:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Hi"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - say-hello
      - say-hi
      - test-variable:
          context: 
            - practice_context